# Generated by Django 4.0.3 on 2022-04-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='papers',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
