# Generated by Django 4.0.3 on 2022-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0002_remove_subject_papers_delete_paper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('topics', models.ManyToManyField(to='school_eyes.topic')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='papers',
            field=models.ManyToManyField(to='school_eyes.paper'),
        ),
    ]
