# Generated by Django 4.0.3 on 2022-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0003_alter_school_class_options_paper_subject_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='coverage',
            field=models.CharField(default=25, max_length=50),
            preserve_default=False,
        ),
    ]
