# Generated by Django 4.0.3 on 2022-05-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0005_remove_subject_papers_subject_paper_delete_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='paper',
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('topics', models.ManyToManyField(to='school_eyes.topic')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='papers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_eyes.paper'),
            preserve_default=False,
        ),
    ]
