# Generated by Django 4.0.3 on 2022-05-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0006_remove_subject_paper_paper_subject_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='topics',
        ),
    ]
