# Generated by Django 4.0.3 on 2022-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0007_remove_paper_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='papers',
        ),
        migrations.AddField(
            model_name='subject',
            name='paper',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
