# Generated by Django 4.0.3 on 2022-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0008_remove_subject_papers_subject_paper_delete_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='paper',
        ),
        migrations.AddField(
            model_name='subject',
            name='papers',
            field=models.ManyToManyField(to='school_eyes.paper'),
        ),
    ]
