# Generated by Django 4.0.3 on 2022-05-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0009_paper_remove_subject_paper_subject_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='papers',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
