# Generated by Django 4.0.3 on 2022-05-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0012_alter_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='coverage',
            field=models.IntegerField(choices=[(0, 'Low'), (25, 'Moderate'), (50, 'Medial'), (75, 'High'), (100, 'Complete')]),
        ),
    ]
