# Generated by Django 4.0.3 on 2022-05-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0013_alter_topic_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
    ]
