# Generated by Django 4.0.3 on 2022-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0014_remove_topic_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='coverage',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
