# Generated by Django 4.0.3 on 2022-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0015_topic_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='coverage',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)]),
        ),
    ]
