# Generated by Django 4.0.3 on 2022-05-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0016_alter_topic_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_eyes.topic')),
            ],
        ),
    ]
