# Generated by Django 4.0.3 on 2022-05-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0017_remove_topic_coverage_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='topic',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='school_eyes.topic'),
        ),
    ]
