# Generated by Django 4.0.3 on 2022-05-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0020_alter_coverage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverage',
            options={'verbose_name_plural': 'coverage'},
        ),
    ]
