# Generated by Django 4.0.3 on 2022-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0021_alter_coverage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
        migrations.AddField(
            model_name='topic',
            name='coverage',
            field=models.ManyToManyField(to='school_eyes.coverage'),
        ),
    ]
