# Generated by Django 4.0.3 on 2022-05-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0022_remove_topic_coverage_topic_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
    ]
