# Generated by Django 4.0.3 on 2022-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0023_remove_topic_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='coverage',
            field=models.ManyToManyField(to='school_eyes.coverage'),
        ),
    ]
