# Generated by Django 4.0.3 on 2022-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0026_alter_coverage_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
        migrations.AddField(
            model_name='topic',
            name='coverage',
            field=models.CharField(choices=[('0', '0'), ('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], default=25, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coverage',
        ),
    ]
