# Generated by Django 4.0.3 on 2022-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0029_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('East', 'East'), ('West', 'West'), ('South', 'South'), ('Central', 'Central')], max_length=15),
        ),
    ]
