# Generated by Django 4.0.3 on 2022-05-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_eyes', '0032_alter_subject_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.OneToOneField(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='school_eyes.subject'),
            preserve_default='TRUE',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='coverage',
            field=models.CharField(choices=[('0', '0'), ('25', '25'), ('75', '75'), ('100', '100')], max_length=10),
        ),
    ]
