# Generated by Django 4.0.3 on 2022-05-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0033_remove_profile_region_profile_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
