# Generated by Django 4.0.3 on 2022-05-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0038_remove_paper_subject_remove_profile_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='school',
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='school_eyes.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(to='school_eyes.subject'),
        ),
        migrations.AddField(
            model_name='school_class',
            name='subjects',
            field=models.ManyToManyField(to='school_eyes.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='school_eyes.subject'),
            preserve_default='TRUE',
        ),
    ]
