# Generated by Django 4.0.3 on 2022-05-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0040_topic_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
    ]
