# Generated by Django 4.0.3 on 2022-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0041_remove_profile_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('0', '0'), ('25', '25'), ('75', '75'), ('100', '100')], max_length=10)),
            ],
        ),
    ]
