# Generated by Django 4.0.3 on 2022-05-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0042_coverage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverage',
            options={'verbose_name_plural': 'coverage'},
        ),
        migrations.RenameField(
            model_name='coverage',
            old_name='text',
            new_name='value',
        ),
    ]
