# Generated by Django 4.0.3 on 2022-05-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0044_coverage_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='topic',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_topic', to='school_eyes.topic'),
            preserve_default=False,
        ),
    ]
