# Generated by Django 4.0.3 on 2022-05-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0045_coverage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_topic', to='school_eyes.topic'),
        ),
    ]
