# Generated by Django 4.0.3 on 2022-05-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_eyes', '0046_alter_coverage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='school',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_topic', to='contenttypes.contenttype'),
        ),
    ]
