# Generated by Django 4.0.3 on 2022-05-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_eyes', '0047_alter_coverage_school_alter_coverage_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='school',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='topic',
        ),
        migrations.AddField(
            model_name='coverage',
            name='content_type',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_topic', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverage',
            name='object_id',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
