# Generated by Django 4.0.3 on 2022-05-30 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_eyes', '0048_remove_coverage_school_remove_coverage_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='added_by',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
