# Generated by Django 4.0.3 on 2022-05-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0049_coverage_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='coverage',
        ),
    ]
