# Generated by Django 4.0.3 on 2022-05-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eyes', '0050_remove_topic_coverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='added_by',
            new_name='owner',
        ),
    ]
