# Generated by Django 4.0.3 on 2022-05-30 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_eyes', '0051_rename_added_by_coverage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='owner',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
